
USE BDPTF;

INSERT INTO Clientes VALUES /*Inserto varios registros juntos*/
(NULL,'EDUARDO','AZCARATE', NULL, 'EL MAESTRO', NULL,'CABA', NULL, NULL),
(NULL,'ANA','PERSICO', NULL, 'EL MAESTRO', NULL,'CABA', NULL, NULL),
(NULL,'OMAR','TONIOLO', NULL, '', NULL,'CABA', NULL, NULL),
(NULL,'NORMA','FUCCENECO', NULL, '', NULL,'CABA', NULL, NULL),
(NULL,'MARIA','BORGO', NULL, '', NULL,'CABA', NULL, NULL),
(NULL,'JORGE','RODRIGEZ', NULL, '', NULL,'CABA', NULL, NULL),
(NULL,'JULIO','OTAZO', NULL, '', NULL,'CABA', NULL, NULL),
(NULL,'ROBERTO','VERON', NULL, 'LIBERTADOR 458', NULL,'CABA', NULL, NULL),
(NULL,'LUIS','GUERINI', NULL, 'ESPAÑA 123', NULL,'CABA', NULL, NULL),
(NULL,'AIDA','TASSO', NULL, 'ALVEAR 789', NULL,'CABA', NULL, NULL),
(NULL, 'CECLIA', 'TISONNI', NULL, '', NULL, 'CABALLITO', NULL, NULL),
(NULL, 'ALEJANDRA', 'LAIÑO', NULL, '', NULL, 'FLORES', NULL, NULL),
(NULL, 'MIA', 'RODRIGUEZ', NULL, '', NULL, 'RECOLETA', NULL, NULL),
(NULL, 'KATY', 'ROSUL', NULL, '', NULL, 'VILLA REAL', NULL, NULL),
(NULL, 'DIANA', 'RIOS', NULL, '', NULL, 'VILLA DEL PARQUE', NULL, NULL),
(NULL, 'MICHAEL', 'ESPINOZA', NULL, '', NULL, 'SAN TELMO', NULL, NULL),
(NULL, 'JORGE', 'DÍAZ', NULL, '', NULL, 'PARQUE CHAS', NULL, NULL),
(NULL, 'AGUSTÍN', 'SOZA', NULL, '', NULL, 'CABA', NULL, NULL),
(NULL, 'SANTIAGO', 'CICCILI', NULL, '', NULL, 'SAAVEDRA', NULL, NULL),
(NULL, 'HUGO', 'AMAYA', NULL, '', NULL, 'SAN CRISTÓBAL', NULL, NULL),
(NULL, 'LAUTARO', 'VILLAGRAN', NULL, '', NULL, 'PUERTO MADERO', NULL, NULL),
(NULL, 'RENZO', 'VILLAVICENCIO', NULL, '', NULL, 'RETIRO', NULL, NULL),
(NULL, 'ESTEFANI', 'BERMEJO', NULL, '', NULL, 'PARQUE CHACABUCO', NULL, NULL),
(NULL, 'ANTONIO', 'GONZALES', NULL, '', NULL, 'NUÑEZ', NULL, NULL),
(NULL, 'SILVINA', 'LOPEZ', NULL, '', NULL, 'MONTE CASTRO', NULL, NULL),
(NULL, 'LILIANA', 'FERNANDEZ', NULL, '', NULL, 'NUEVA POMPEYA', NULL, NULL),
(NULL, 'ARMANDO', 'GOMEZ', NULL, '', NULL, 'LINIERS', NULL, NULL),
(NULL, 'MOISÉS', 'SOSA', NULL, '', NULL, 'LA BOCA', NULL, NULL),
(NULL, 'DAVID', 'TORRES', NULL, '', NULL, 'CONSTITUCIÓN', NULL, NULL),
(NULL, 'ROXANA', 'RUIZ', NULL, '', NULL, 'COLEGIALES', NULL, NULL),
(NULL, 'CARLOS', 'CASTRO', NULL, 'AV. BOEDO 1500', NULL, 'BOEDO', NULL, NULL),
(NULL, 'ANDRÉ', 'ROMERO', NULL, 'AV.CABILDO', NULL, 'BELGRANO', NULL, NULL),
(NULL, 'FRANCO', 'VAZQUEZ', NULL, '', NULL, 'BARRACAS', NULL, NULL),
(NULL, 'ANDREA', 'ACOSTA', NULL, 'AV. PUEYRREDON', NULL, 'BALVANERA', NULL, NULL),
(NULL, 'ARTURO', 'GIMENEZ', NULL, 'MEDRANO 900', NULL, 'ALMAGRO', NULL, NULL);


/*Insertar código de barrio a clientes desde barrios*/